# 多环境配置文件激活属性
spring:
  profiles:
    active: dev
  mvc:
    servlet:
      load-on-startup: 1
server:
  compression:
    enabled: true
# Mybatis配置
mybatis:
  configLocation: classpath:mybatis.xml
  mapper-locations: classpath:com/example/demo/**/mapper/*.xml